### ISSUE TITLE
Doubt abou the app

### ISSUE THREAD

**Issue by sanbnl** [kkrisst/YoutubeMostPopular#1]
Is the application working for you ?

**Comment by kkrisst** [comment]
Hi!
The application is unfinished, currently on hold.

**Comment by sanbnl** [comment]
OK, i am developing an application that nearly has the purpose, this why you app interested me, i have one question of you can help me i would be so grateful, do you know how can i get a youtube video category once i have the query result ?

**Comment by kkrisst** [comment]
I'm not sure what your query result could be, but I assume you sent a **youtube/v3/docs/videos/list** request. If you set the **part** field to **snippet**, the response will contain the category to each video.
To find the available categories, use **/youtube/v3/docs/videoCategories/list**.

**Comment by sanbnl** [comment]
Thank you very much
